/** The body you live in, rest and health. */
export const body = [
  'Your body has carried you through every day of your life. Thank it.',
  'When did you last go to bed early because you wanted to?',
  'How are you, really? Not the polite answer.',
  'What is your body trying to tell you?',
  'Take three slow breaths before you do anything else.',
  'When did you last move just for the joy of it?',
  'You only get one body. How are you treating it?',
  'Drink a glass of water. Then keep reading.',
  'When did you last feel strong?',
  'Is there a check-up you keep putting off?',
  'Sleep is not a luxury.',
  'What would you do today if you listened to your tiredness?',
  'Walk somewhere you would normally drive.',
  'How does your body feel right now? Notice it before you move on.',
  'Which small habit would your eighty-year-old self thank you for?',
  'What are you eating in a hurry that deserves to be tasted?',
  'When did you last dance?',
  'Stand up and stretch. Your body keeps count.',
  'Rest before you need to.',
  'Is there pain you’ve decided to ignore?',
  'Your future self is built by what you do today.',
  'When did you last go outside without a reason?',
  'How many more years do you want to be able to climb stairs?',
  'Health is invisible until it’s gone.',
  'What does your body love that you rarely give it?',
  'Go to sleep ten minutes earlier tonight.',
  'When did you last swim, run or climb just to feel alive?',
  'The body you complain about is the one that keeps you here.',
  'Put your hand on your chest. That beat has never stopped for you.',
  'What would you stop doing to your body if you loved it?',
  'Unclench your jaw. Drop your shoulders.',
  'When did you last spend a whole day off your screens?',
  'How do you treat yourself when you’re unwell?',
  'Would you treat a friend’s body the way you treat yours?',
  'Is stress living somewhere in your body right now?',
  'Take the stairs, and notice that you can.',
  'When did you last eat a meal slowly, with someone you love?',
  'Your breath is always here. Come back to it.',
  'What does rest look like for you?',
  'Is there an ache you’ve carried so long you’ve stopped noticing it?',
  'Lie on the grass or the floor for five minutes and do nothing.',
  'Which part of you needs gentleness today?',
  'What would it take to feel rested?',
  'Look up from the screen and let your eyes find something far away.',
  'When did you last feel the sun on your face?',
  'You will not always be able to do what you can do now.',
  'Which activity would you miss most if your body could no longer do it?',
  'Is there something you’d love to do while your body still lets you? Do it soon.',
  'Is exhaustion your baseline? Since when?',
  'What would change if you slept well for a month?',
  'Eat something that grew from the ground today.',
  'When did you last feel truly at home in your body?',
  'A walk can untangle what thinking cannot.',
  'How many more times will you be able to run for the joy of it?',
  'Your body is not a machine to be optimised. It is you.',
  'Put down what you’re carrying, even for a moment.',
  'Notice your posture right now, without judging it.',
  'When did you last cry? It’s allowed.',
  'Who in your life needs to hear “take care of yourself”? Are you one of them?',
  'What would a kinder morning routine look like?',
  'Is there a medical question you’re afraid to ask?',
  'Your body keeps the score of every sleepless night.',
  'When did you last do nothing and not feel guilty about it?',
  'What would you like your body to still do at eighty?',
  'Stand outside for one minute tonight and look up.',
  'Tiredness is information, not failure.',
  'What is one thing you could do this week just for your health?',
  'Take a slower walk than usual today.',
  'When did you last feel your heart race for a good reason?',
  'Which of your comforts is quietly costing you?',
  'You are allowed to stop before you are empty.',
  'Close your eyes for ten seconds. Listen.',
  'What would it feel like to wake up without an alarm?',
  'When did you last touch the sea, a river, a tree?',
  'Your body is older today than it has ever been. Be gentle with it.',
  'Notice one thing your senses are telling you right now.',
  'Is there a small pain you could fix today?',
  'Rest is how you last.',
  'Would you describe your life as sustainable?',
  'Take a real lunch break today.',
  'Which of your senses do you most take for granted?',
  'Taste the next thing you eat.',
  'What does your breathing feel like when you’re happy?',
  'You were once a child who couldn’t sit still. When did you stop moving?',
  'What would you stop doing if you trusted your body’s signals?',
  'A good night’s sleep solves more than you think.',
  'When did you last feel light?',
  'Hold something warm with both hands and notice it.',
  'What is your body grateful for today?',
  'Let tonight be early and quiet.',
  'Your life is lived through your body. It deserves your attention.',
  'What would you do today if you felt completely well?',
  'Move a little, every day, for the rest of your life.',
  'When did you last stretch in the morning like a cat?',
  'Feel the ground under your feet.',
  'What would a year of better sleep change about your life?',
  'Do you rest, or do you just collapse?',
  'Is there something you would do more of if you had more energy?',
  'Breathe out longer than you breathe in.',
  'Be proud of what your body has survived.',
] as const
