/** Fear, risk and the things left unsaid or undone. */
export const courage = [
  'What would you do today if you weren’t afraid?',
  'What are you pretending not to know?',
  'Which fear has been making your decisions?',
  'What is the thing you most want to say but haven’t?',
  'Is there a leap you keep measuring instead of taking?',
  'What would you regret more: trying and failing, or never trying?',
  'Whose opinion are you living your life around?',
  'The worst that can happen is usually survivable.',
  'What is one small brave thing you could do today?',
  'Which door have you been standing in front of for too long?',
  'What would you do if no one would ever find out?',
  'What are you waiting for permission to do?',
  'Fear is often a sign you care. What do you care about here?',
  'Which comfortable thing is keeping you small?',
  'What would the bravest version of you do next?',
  'Is there a question you’re afraid to ask because of the answer?',
  'Say no to something today that you would usually say yes to.',
  'Say yes to something you would usually say no to.',
  'What is the story you tell yourself about why you can’t?',
  'Who would you be if you stopped playing it safe?',
  'What would you attempt if failure were only information?',
  'Is there a truth you need to tell someone?',
  'Is there a truth you need to tell yourself?',
  'Courage is being afraid and going anyway.',
  'What have you already survived that you once thought you couldn’t?',
  'Which risk would you take if you had one year to live?',
  'What would you wear, say or do if you stopped worrying about looking foolish?',
  'You will be embarrassed far less than you fear.',
  'What are you avoiding by staying busy?',
  'Is there a change you know you need to make?',
  'Ask for what you want today.',
  'What would happen if you let people see the real you?',
  'Which of your beliefs have you never questioned?',
  'What could you start today, badly, just to begin?',
  'Where are you choosing comfort over growth?',
  'What would you do if you trusted yourself completely?',
  'Is there something you’ve outgrown but haven’t left?',
  'Speak up once today where you would usually stay silent.',
  'What is one uncomfortable conversation that would change things?',
  'Doing the brave thing gets easier each time.',
  'What would you tell a friend who was as afraid as you are?',
  'Which dream have you quietly given up on? Is it really gone?',
  'What if you’re more capable than you think?',
  'Is there something you want that you’ve never said out loud?',
  'Say one of your hopes out loud today, even if only to yourself.',
  'What are you holding on to because letting go is frightening?',
  'Which of your “shoulds” are actually someone else’s?',
  'What would you do if you stopped waiting to feel ready?',
  'The perfect moment is a myth. There is only now.',
  'What small risk could make this week memorable?',
  'Is there a decision you’ve been avoiding? Make it, or decide when you will.',
  'What would you do if you believed you deserved it?',
  'What would change if you stopped apologising for who you are?',
  'Which of your fears is older than you are?',
  'The things you don’t do will weigh more than the things you do.',
  'Who would you call if you were brave enough?',
  'What would it cost you to try? What will it cost you not to?',
  'Is there a boundary you need to set?',
  'Where have you been settling?',
  'What could you do this week that would scare you a little?',
  'Your comfort zone is comfortable. It is also a zone.',
  'What would your life look like if you trusted it more?',
  'Is there an old dream worth dusting off?',
  'Walk towards the thing you’ve been walking around.',
  'You don’t have to be fearless. You just have to move.',
  'What would you risk for the life you actually want?',
  'Which conversation would you have today if you knew it would go well?',
  'What would you create if you weren’t afraid of it being bad?',
  'Is there a version of your life you are too scared to imagine?',
  'Imagine the life you would have if you weren’t afraid. Stay there for a minute.',
  'Which “what if” keeps coming back to you?',
  'What are you tolerating that you don’t have to?',
  'What would you stop hiding?',
  'What are you afraid people would think if they knew what you want?',
  'You are allowed to change your mind about your life.',
  'Take one step today toward the thing that scares you.',
  'What would you do if you knew it was okay to fail?',
  'Is there a “no” you’ve been too polite to say?',
  'Which excuse have you used the longest?',
  'The regret of not trying lasts longer than the sting of failing.',
  'What would you do if you didn’t need anyone’s approval?',
  'Is fear protecting you here, or just keeping you still?',
  'What is the bravest thing you’ve ever done? What made it possible?',
  'You have been brave before. You can be brave again this week.',
  'What adventure is still waiting for you?',
  'Is there a place you’ve always wanted to go? What stops you?',
  'Which safe choice have you regretted?',
  'What would your life look like if you stopped shrinking?',
  'Is there something you need to walk away from?',
  'Tell someone about the dream you’ve never shared.',
  'What could go right?',
  'You are running out of time to be afraid of the wrong things.',
  'Do the thing, then feel the fear afterward.',
  'What would you regret not having said, if today were the last day?',
  'Who would you forgive if you weren’t afraid of being hurt again?',
  'Which new beginning have you been postponing?',
  'Is there an answer you’re afraid to hear? You deserve to know it.',
  'What would you do with a little more nerve?',
  'Courage is contagious. Who could you inspire today?',
  'Begin before you feel ready.',
] as const
