/** Regret, forgiveness and letting go. */
export const forgiveness = [
  'What are you still carrying that you could put down?',
  'Is there someone you need to forgive so that you can move on?',
  'Have you forgiven yourself for the thing you still think about?',
  'Which old mistake still decides how you act today?',
  'What would you do differently, and what can you still do about it?',
  'Who deserves a second chance from you?',
  'Is there an apology you owe that has waited long enough?',
  'Being right matters less than being at peace.',
  'What are you holding against someone who has probably forgotten it?',
  'Resentment is a heavy thing to carry for someone else.',
  'Which regret could you still turn into an action?',
  'What would it take to let go of an old grievance today?',
  'Is there a version of your past you keep arguing with?',
  'You did the best you could with what you knew then.',
  'Which door have you closed that you could reopen?',
  'What are you punishing yourself for?',
  'Forgiveness doesn’t mean it was okay. It means you are free.',
  'Is there a friendship that ended over something small?',
  'What would you say to the person you were five years ago?',
  'Which of your failures taught you the most?',
  'What would letting go look like, in practice, today?',
  'Is there someone who hurt you who was also hurting?',
  'What part of your story are you ready to stop retelling?',
  'Mistakes are proof that you tried.',
  'Who have you misjudged?',
  'Is there a family rift that time could still heal?',
  'Could you be gentler with yourself about the past?',
  'What would you forgive in a friend that you won’t forgive in yourself?',
  'The past cannot be changed, but its grip can loosen.',
  'Which of your regrets is really a lesson?',
  'Is there a letter you could write and never send, just to let it go?',
  'What would change if you stopped keeping score?',
  'Who are you still angry at? What does that anger protect?',
  'You are not the worst thing you have ever done.',
  'What would you like to be forgiven for?',
  'Is it time to stop waiting for an apology that may never come?',
  'Which bridge was worth burning, and which wasn’t?',
  'What have you learned from someone who hurt you?',
  'Holding a grudge is letting someone live in your head for free.',
  'Is there a “sorry” you could say today?',
  'Which old version of you do you need to make peace with?',
  'What would it feel like to wish someone well who wronged you?',
  'Regret points to what you value. What is yours pointing to?',
  'Is there someone you pushed away that you would like back?',
  'What would you tell a friend who made the mistake you made?',
  'Let today be lighter than yesterday.',
  'Which misunderstanding could a single conversation clear up?',
  'Is there a decision you keep reliving? It’s already been made.',
  'What would you regret not having forgiven, if it were too late?',
  'People change. Have you allowed the people around you to change?',
  'Have you allowed yourself to change?',
  'What would you stop blaming yourself for if you looked at it fairly?',
  'Which memory still makes you wince? Can you soften it with understanding?',
  'Is there an old argument that no longer matters?',
  'What if you let someone be imperfect today?',
  'Which silence has gone on too long?',
  'Do you forgive as easily as you want to be forgiven?',
  'What could you release today that no longer serves you?',
  'There is still time to make some things right.',
  'Is there something you need to hear “it’s okay” about?',
  'Whatever you are carrying today, it’s okay to set it down for a while.',
  'What part of your life are you still apologising for?',
  'Which “if only” do you replay the most?',
  'What would you do today to reduce tomorrow’s regrets?',
  'Is there someone whose side of the story you never heard?',
  'Can you be grateful for what a painful time gave you?',
  'What would healing look like between you and someone you’ve lost touch with?',
  'Not every relationship needs to be saved. Some need to be released.',
  'What are you still trying to prove to someone from your past?',
  'Is there a kindness you withheld that you could offer now?',
  'Who would you like to make things right with before the year ends?',
  'Your past self was doing their best. So is your present self.',
  'What would it take to stop replaying that moment?',
  'Which grudge is costing you more than it’s worth?',
  'What have you never said sorry for, because it felt too small?',
  'Could you forgive without needing to forget?',
  'What if the thing you regret led you somewhere you’re glad to be?',
  'Is there someone you haven’t forgiven because they never asked?',
  'Which wound are you ready to let close?',
  'What would you want someone to forgive you for, if you were gone?',
  'Anger is a guest. It doesn’t have to move in.',
  'Is there an old friend who would be glad to hear from you, despite everything?',
  'Which disappointment are you ready to stop carrying?',
  'What would you do with the energy you spend on resentment?',
  'Could you send a kind word to someone you fell out with?',
  'What story about yourself are you ready to rewrite?',
  'Is your pride worth the distance it keeps?',
  'Which lesson did you learn the hard way? Honour it.',
  'The people who hurt you are also running out of time.',
  'What would you like to be free of by the end of this year?',
  'Is there a mistake you can still make amends for?',
  'Forgive the person you were when you didn’t know better.',
  'What if the kindest thing you could do today is let it go?',
  'Which of your judgements about someone could be wrong?',
  'Do you need someone’s forgiveness, or your own?',
  'What would you like to leave behind in this season of your life?',
  'Is there a phone call that could end a years-long silence?',
  'Which regret would hurt most on your last day? Can you act on it now?',
  'You can begin again at any moment.',
  'Make peace while there’s still time to make it.',
] as const
