/** Noticing what is already good. */
export const gratitude = [
  'What is something good in your life you haven’t noticed lately?',
  'Name three things you’re grateful for, right now.',
  'What small comfort would you miss most if it disappeared?',
  'Someone once hoped for the life you have now.',
  'What made you smile yesterday?',
  'Who are you grateful for, and do they know?',
  'What went right today?',
  'What do you have now that you once wished for?',
  'Clean water, a roof, this moment. Not everyone has them.',
  'Which ordinary thing would feel like a luxury if you lost it?',
  'What are you grateful your body can still do?',
  'What is the best thing that happened to you this year?',
  'Who has been kind to you recently?',
  'Which lucky break changed your life?',
  'Thank someone today for something small.',
  'What is something you love about where you live?',
  'Which book, song or film changed you?',
  'Who made your life easier this week without being asked?',
  'What mistake turned out to be a gift?',
  'What do you love about the person you’ve become?',
  'Which of your daily comforts did your grandparents never have?',
  'Look at what you have before you look at what you want.',
  'What made today better than it could have been?',
  'Who has forgiven you?',
  'What are you grateful to have survived?',
  'Which memory still makes you happy every time?',
  'What would you miss about today if it were your last?',
  'Enough is a feast.',
  'Which part of your routine do you secretly love?',
  'What is the kindest thing anyone ever did for you?',
  'Who do you owe a thank-you note?',
  'Write a thank-you note today, even if you never send it.',
  'What is beautiful about today, even if it’s been hard?',
  'Which friend has shown up for you when it mattered?',
  'What do you get to do that you once only dreamed of?',
  'What is one thing you’re glad you didn’t give up on?',
  'Gratitude turns what you have into enough.',
  'Who laughed with you this week?',
  'What small pleasure is waiting for you later today?',
  'Which teacher do you still think of?',
  'Which stranger was kind to you once?',
  'What did you learn this week that made you better?',
  'What view do you love?',
  'What sound always makes you feel at home?',
  'What would you tell your younger self to be grateful for?',
  'Who took a chance on you?',
  'What’s one thing about your life that is quietly working?',
  'Which hardship made you kinder?',
  'Who makes you laugh without trying?',
  'What would you save first in a fire, apart from people?',
  'Which of your belongings holds a memory you could never replace?',
  'What do you have enough of?',
  'Look at your hands. Think of everything they’ve made and held.',
  'What would you thank today for?',
  'Who taught you something you’re glad to know?',
  'Which meal do you remember with pleasure?',
  'What is something you used to struggle with that’s easy now?',
  'Who in your family are you most grateful for?',
  'What is good about this exact moment?',
  'Which place in the world are you glad you’ve seen?',
  'What made you feel loved recently?',
  'Say thank you like you mean it today.',
  'Which old photo makes you happy?',
  'What do you love about being alive?',
  'What is the best part of your mornings?',
  'What would you miss about your worst day?',
  'Who helped you become who you are?',
  'What luck have you had that you rarely acknowledge?',
  'Which song reminds you of someone you love?',
  'What is one thing about your life you’d fight to keep?',
  'Who has been patient with you?',
  'The ordinary is extraordinary to someone who has lost it.',
  'What are you grateful to still have time for?',
  'What made you proud this month?',
  'Which friend do you feel lucky to have met?',
  'What gift did someone give you that wasn’t a thing?',
  'What would you tell the world you’re thankful for, if you had to?',
  'Which moment this week would you frame, if you could?',
  'What do you appreciate about the person you share your days with?',
  'Who would be happy to know they made a difference to you?',
  'What’s the best advice you ever received?',
  'Which season do you love, and why?',
  'What do you love doing that costs nothing?',
  'Who has believed in you when it mattered?',
  'What part of your past are you grateful to have left behind?',
  'Which small daily thing brings you joy?',
  'Who has made you feel understood?',
  'What would you like to thank yourself for?',
  'You woke up today. That was not guaranteed.',
  'What is the best thing about the place you are sitting right now?',
  'Who made you a better person just by knowing them?',
  'What’s something you get to look forward to this week?',
  'Which of your freedoms do you take for granted?',
  'What has life given you that you didn’t ask for?',
  'Count what you have before counting what you lack.',
  'Who would you like to thank before it’s too late?',
  'What kindness can you pass on today?',
  'Which moment of your life would you gladly live again?',
  'What is good, right now, without needing to change anything?',
  'You have been given one more day. What will you do with it?',
] as const
