/** Values, purpose and what matters most. */
export const meaning = [
  'What matters to you most, and does your week reflect it?',
  'If you could only keep three things in your life, which would they be?',
  'What do you want your life to have been about?',
  'What gives your days meaning?',
  'What would you stand up for, even alone?',
  'Which of your values have you been neglecting?',
  'What do you want to be remembered for by the people you love?',
  'What does a good life look like to you, not to anyone else?',
  'What would you do with your life if you had nothing to prove?',
  'Which of your goals would still matter if no one ever knew about them?',
  'What makes you feel most alive?',
  'Are you living by your own values or borrowed ones?',
  'What small thing could you do today that fits the person you want to be?',
  'What would you want written on your gravestone?',
  'What do you love so much you forget to eat?',
  'Who do you want to become in the time you have left?',
  'What would you do if you were sure it mattered?',
  'Which part of your life feels most like yours?',
  'What would you fight to protect?',
  'What would you give up to have more of what matters?',
  'Is there something you believe in that you never act on?',
  'Which moments of your life have felt most meaningful?',
  'What would your life look like if you lived it on purpose?',
  'What are you here to give?',
  'What does “enough” mean to you?',
  'Which of your possessions truly matter to you?',
  'What kind of person do you want to be when things get hard?',
  'What would you teach the world if you had one minute?',
  'What legacy are you building with the way you spend your days?',
  'What would make you feel your life was well spent?',
  'Which of your everyday choices would you be proud to explain?',
  'What do you want more of in your life, and less of?',
  'What part of you have you been ignoring?',
  'Which dream is still worth chasing?',
  'What would you do if you knew your life was a story people would read?',
  'What does it mean to you to live well?',
  'What would you like to do for someone who can never repay you?',
  'Where do you feel most like yourself?',
  'What do you want to understand before you die?',
  'What would you create if it could outlive you?',
  'Is your life a reflection of what you say matters?',
  'What are you here for, beyond what you do for a living?',
  'What would you do differently if you took your values seriously today?',
  'What brings you peace?',
  'Which of your beliefs have you earned, and which did you inherit?',
  'What would you like the world to have a little more of because of you?',
  'Who are you when no one is watching?',
  'What is one thing you could do this week that matches who you want to be?',
  'Which of your habits reflect your values, and which betray them?',
  'What would it mean to live fully?',
  'What do you care about that you rarely talk about?',
  'If your life had a title, what would you want it to be?',
  'What would you still do if you were the last person on earth?',
  'Which kindness would you like to be known for?',
  'What would you do if you took your own happiness seriously?',
  'What is the most important thing you’ve learned so far?',
  'Who would you like to become for the people who depend on you?',
  'What do you want to protect in the world?',
  'What would you do with your life if you trusted your own judgement?',
  'Which moments would you want to relive if you had only a few more days?',
  'What are you grateful to have been part of?',
  'What do you want your days to add up to?',
  'Which cause would you give an hour to each week?',
  'What makes a day feel worth living to you?',
  'What would you want your grandchildren to know about you?',
  'Is there a purpose you’ve been too busy to pursue?',
  'What would you say your life has been about so far? Is that what you want?',
  'Which values would you want to pass on?',
  'Who do you want to be for your friends?',
  'What part of your life needs more of your heart?',
  'What would it take to live without regrets from here on?',
  'Which question about your life do you keep avoiding?',
  'What do you hope people feel when they think of you?',
  'Are you busy with what matters, or with what’s urgent?',
  'What would you do if you were brave enough to live your values?',
  'What is one thing you want to do before you die that you haven’t told anyone?',
  'What would make this ordinary day meaningful?',
  'Which person do you most want to make proud? Why?',
  'What does your life say about what you value?',
  'What would you like to have done with your life that you still can?',
  'Where are you needed?',
  'What would you work on even if it took the rest of your life?',
  'Which of your gifts are you not using?',
  'What do you want to be true about your life at the end?',
  'Is there a way to live that would make you proud every day?',
  'What would you be willing to be uncomfortable for?',
  'What kind of ancestor do you want to be?',
  'What does your heart keep coming back to?',
  'Which life would you choose if you could choose again?',
  'Which parts of your life would you choose again? Choose them again today.',
  'What would give you peace at the end, looking back?',
  'Which of your choices today would your wisest self make?',
  'What would you do if you stopped waiting for meaning to find you?',
  'What is the story you want your life to tell?',
  'What makes your life yours?',
  'Is there something beautiful you could add to the world this week?',
  'What do you want to leave behind: things, or people who are better for knowing you?',
  'What is worth your one life?',
  'What would you regret not having cared about?',
  'Live as if it matters. It does.',
] as const
