/** Remembering that you will die, and letting it clarify the rest. */
export const mortality = [
  'Remember that you will die. What does that make clear today?',
  'If today were your last day, would you want to do what you are about to do?',
  'You will not be here forever. Neither will anyone you love.',
  'What would you do differently if you had a year left?',
  'What would you do differently if you had a month left?',
  'What would you do differently if you had a week left?',
  'Your life is finite. That is what makes it precious.',
  'What would you want to have done by the time you die?',
  'If you died tonight, what would be left unsaid?',
  'What are you taking for granted because you assume there will be time?',
  'Death is certain. The date is not.',
  'How would you live if you truly believed your time was limited?',
  'Everyone you know is running out of time, just like you.',
  'What would you want your last conversation to be about?',
  'Which fears will seem small on your last day?',
  'What will matter when you look back from the very end?',
  'You are one day closer to the end than yesterday. Make it a good one.',
  'Would you be at peace if this were your final year?',
  'What would you stop worrying about if you remembered you will die?',
  'Imagine your funeral. What would you want people to say?',
  'What would the people who love you want you to do with your remaining time?',
  'Every ending you’ve lived through was practice for the last one.',
  'If you knew the exact day you would die, how would you live until then?',
  'What will you wish you had spent more time on?',
  'What will you wish you had spent less time on?',
  'How many more times will you see the sea, your friends, your parents?',
  'The hourglass never runs backwards.',
  'Let the shortness of life make you braver, not more afraid.',
  'What legacy would you leave if your time ended this year?',
  'What would you want to be doing when your time comes?',
  'Is there something you want to do before you die that you could do this month?',
  'Knowing you will die, what do you refuse to waste?',
  'What would you tell your family if you had one hour left?',
  'Life is short. That is not a reason to rush. It is a reason to choose.',
  'You are alive right now. What will you do with that?',
  'Would you be proud of this day if it were your last?',
  'Which of today’s worries will outlive you?',
  'Death reminds us what is worth living for. What is it, for you?',
  'What would you want your final years to feel like?',
  'Are you living as if you have forever?',
  'What would you do today if tomorrow were not promised?',
  'Tomorrow is not promised.',
  'Which people would you want to see if you knew your time was short?',
  'What are you waiting for that you might not live to see?',
  'The grave does not care about your to-do list.',
  'What would you regret on your deathbed about today?',
  'How do you want to die? How must you live for that to happen?',
  'Every breath is one of a limited number. Take this one slowly.',
  'What would you forgive if you knew you would die soon?',
  'What if you lived this year as if it were your last good one?',
  'Which of your plans assume a future you can’t be sure of?',
  'Mortality is the reason everything you do matters.',
  'What would your life look like if you took your death seriously?',
  'The people who died young would give anything for the day you have now.',
  'What small joy would you want in your last days? Could you have it today?',
  'What would you do if you knew you had exactly as long as you have?',
  'Every day you wake up is borrowed from a future you’ll never fully see.',
  'What unfinished business would bother you most at the end?',
  'Which of your ambitions would you still care about at ninety?',
  'Death does not make life meaningless. It makes it urgent.',
  'Where would you want to be at the end?',
  'Who would you want holding your hand?',
  'Remember: this too will end. Both the good and the hard.',
  'Would you trade your remaining years for more money? Then why do you, day by day?',
  'Life is not a rehearsal.',
  'What are you afraid of losing? One day you will lose everything. Love it now.',
  'What would the old version of you, near the end, tell you today?',
  'Which parts of your life will still feel important at the very end?',
  'If you had one more day with someone you’ve lost, what would you do?',
  'Spend an hour with someone you love as if it were your last with them.',
  'Knowing you will die, what are you still waiting for?',
  'Let the finite nature of life make you kinder.',
  'The end is the same for everyone. The days before it are yours to shape.',
  'Would you be content if your life ended exactly as it is now?',
  'What would it take to be ready?',
  'You will never have more time than you have right now.',
  'What does remembering death do for you today?',
  'How would you spend your last ordinary Tuesday?',
  'What would you want to be doing more of in the years you have left?',
  'The days you have left are fewer than you think, and more than you use.',
  'Live today in a way you would be glad to remember at the end.',
  'Which goodbyes have you been putting off?',
  'What would you do if you knew this was the last spring you would see?',
  'You will die. Until then, live.',
  'What would you want the last chapter of your life to be about?',
  'How many more autumns do you have? Watch this one.',
  'Death is the one appointment you will not miss.',
  'What would make you ready to go, whenever it comes?',
  'Which of your fears would disappear if you truly accepted that life ends?',
  'Life is a loan, not a gift you keep.',
  'What would you do today if you knew it was one of your last ten thousand?',
  'Hold loosely what you cannot keep. Hold tightly who you love.',
  'Every sunset you see is one fewer you will see.',
  'When you are gone, what will still be here because of you?',
  'What would dying without regret require of you now?',
  'You don’t know how many days are left. Treat this one as if it counts.',
  'At the end, only love and time will have mattered. How are you spending both?',
  'Memento mori: remember that you will die. Now go and live.',
  'The sand is falling. What will you do before it runs out?',
  'You are here. For now. Let that be enough to begin.',
] as const
