/** The people in your life, and the time you have with them. */
export const people = [
  'Who haven’t you called in a while?',
  'When did you last tell someone you love them, and mean every word?',
  'Who would you want beside you on your last day?',
  'Someone is thinking about you right now. Who might it be?',
  'Whose voice would you most miss hearing?',
  'Is there a conversation you keep postponing?',
  'Who taught you something you still use every day?',
  'Have you thanked the people who shaped you?',
  'Your parents are getting older too.',
  'Who makes you feel most like yourself?',
  'Which friendship have you let drift without meaning to?',
  'What would you say to someone you love if you knew it was the last time?',
  'Who needs you more than they let on?',
  'Whose birthday are you about to forget?',
  'Is there someone you should visit while you still can?',
  'Who do you take for granted because they are always there?',
  'Listen more closely to the next person who talks to you.',
  'A short message today can mean more than a long one someday.',
  'Who would be surprised to hear that you think of them?',
  'Which of your friends have you never told why you value them?',
  'Who have you been meaning to forgive?',
  'Who have you been meaning to apologise to?',
  'The people you love will not always be a phone call away.',
  'What is one thing you could do for someone today, unasked?',
  'When did you last laugh until it hurt, and who were you with?',
  'Who would you like to know better before it’s too late?',
  'Do the people closest to you know what you’re going through?',
  'Whose life would be different if you had never met?',
  'Ask someone a question you have never asked them.',
  'Who has stood by you when it was hard?',
  'Have you shown up for the people who show up for you?',
  'Which family story would be lost if no one wrote it down?',
  'Ask an older relative about their life before you were born.',
  'Who in your life is quietly lonely?',
  'Would the people you love recognise the person you are at work?',
  'Whose advice do you wish you had taken?',
  'Who would you call first with good news? Call them for no reason.',
  'Is there a grudge that has outlived its reason?',
  'Who do you owe a letter?',
  'What would your best friend say you need to hear today?',
  'Who have you been too busy to see?',
  'Which relationship deserves more of your attention this week?',
  'What do you hope your children, or anyone younger, learn from you?',
  'Who made you feel safe as a child?',
  'Are you kinder to strangers than to the people you love?',
  'When did you last give someone your full attention?',
  'Who believed in you before you believed in yourself?',
  'The time you spend with someone is time they spend with you.',
  'Who would be glad just to hear your voice?',
  'What small ritual could you share with someone you love?',
  'Is there someone you only see at funerals?',
  'Who would you like to make peace with?',
  'Who deserves to hear “you were right”?',
  'Who deserves to hear “I was wrong”?',
  'Which friend would you like to grow old alongside?',
  'Hold the next hug a little longer.',
  'Who have you not yet introduced to the people you love?',
  'What would you like to do with someone before one of you is gone?',
  'Who taught you how to love, and how?',
  'Whose kindness have you never repaid?',
  'Are you the friend you would want to have?',
  'Who could use your help but would never ask?',
  'When you are gone, who will tell your stories?',
  'Which conversation from years ago do you still think about?',
  'Who would you like to thank before the year is out?',
  'Put your phone away the next time someone is talking to you.',
  'How many more times will you see your parents? Make each one count.',
  'Who have you been judging without knowing their story?',
  'Make plans with someone instead of saying “we should”.',
  'Who brings out the best in you? Spend more time with them.',
  'Who brings out the worst in you? Notice it.',
  'What does someone you love need to hear from you?',
  'Who would you like to know that you’re proud of them?',
  'Is there a friend you lost touch with for no real reason?',
  'Write down one thing you love about someone, and send it.',
  'Who do you picture when you think of home?',
  'Whose handwriting would you give anything to see again?',
  'Who have you never really listened to?',
  'Some goodbyes don’t announce themselves.',
  'Who in your family do you understand better now than you did?',
  'What did you inherit from the people before you, besides things?',
  'Who would you like to spend an ordinary afternoon with?',
  'Who are you still trying to impress, and why?',
  'Is there someone you love who doesn’t know it?',
  'When did you last ask a friend how they really are?',
  'Who have you outgrown, and who have you grown with?',
  'Who makes the world gentler just by being in it?',
  'Invite someone over this week.',
  'Who have you been too proud to reach out to?',
  'Which of your relationships would you like to begin again?',
  'Who will you think of when you are very old?',
  'Tell a teacher, wherever they are now, what they meant to you.',
  'Who would notice if you went quiet?',
  'Who do you need to stop waiting for?',
  'The people you love are not a background to your life. They are the life.',
  'Who have you promised to see “soon”?',
  'Which friendship would you fight for?',
  'What would you want someone to remember about the time you spent together?',
  'Who could you make laugh today?',
  'Ask someone what they are looking forward to, and really listen.',
] as const
