/** Attention, and being here for the life you already have. */
export const presence = [
  'Where is your mind right now?',
  'What can you hear, if you stop and listen?',
  'Look around. What have you stopped noticing?',
  'This is the only moment you ever actually have.',
  'What are you half-doing right now?',
  'When did you last do one thing at a time?',
  'What would it feel like to be fully here for the next ten minutes?',
  'Notice the light in the room.',
  'What colour is the sky today?',
  'Put the phone face down for the next conversation.',
  'Where do you go in your head when you’re bored?',
  'Name three things you can see that you didn’t choose to look at.',
  'What is the quietest sound around you?',
  'Is your attention yours, or has someone else taken it?',
  'What would you notice on your way home if you looked up?',
  'The present is not a waiting room for the future.',
  'Are you living this day or rehearsing tomorrow?',
  'When did you last watch something without filming it?',
  'Taste your coffee today.',
  'What are your hands doing right now?',
  'Can you let this moment be enough?',
  'What would you see if you looked at a familiar place for the first time?',
  'When did something last take your breath away?',
  'How much of today have you spent somewhere other than where you are?',
  'Notice the next time you reach for your phone. What were you avoiding?',
  'Sit for one minute without doing anything.',
  'What is beautiful within ten metres of you?',
  'Ordinary moments are most of what you will get. Look at this one.',
  'What is the weather doing? When did you last feel it?',
  'Listen to one whole song without doing anything else.',
  'Where do you feel calm? When were you last there?',
  'You can’t be anywhere else right now. So be here.',
  'What small thing happened today that you almost missed?',
  'Walk slowly enough to notice the walk.',
  'What does this room smell like?',
  'When did you last watch the clouds move?',
  'Notice your next breath, all the way in and all the way out.',
  'Is your mind in the past, the future, or here?',
  'What would you notice if you were visiting your own town as a stranger?',
  'Attention is the rarest form of generosity. Who gets yours?',
  'What are you looking forward to so much that you’re missing today?',
  'Look at someone you love as if you were seeing them for the last time.',
  'Eat your next meal without a screen.',
  'Which of your senses is quietest right now? Turn it up.',
  'When did you last just sit with a friend in silence?',
  'What would this moment look like as a memory?',
  'Wherever you go, there you are.',
  'The next five minutes: can you give them all your attention?',
  'What have you been skimming through that deserves to be read slowly?',
  'Look out of the nearest window for a full minute.',
  'Right now, nothing is required of you but to breathe.',
  'When did you last notice the first warm day of the year?',
  'What is one thing you’re grateful to be able to see?',
  'How often do you check the time? What are you waiting for?',
  'Put everything down and look at what’s in front of you.',
  'What would you notice if you walked barefoot today?',
  'Which moments today felt like they were really yours?',
  'Distraction is easy. Presence is a choice.',
  'Notice how the air feels on your skin.',
  'You will not get this Tuesday again. Or whatever day it is.',
  'When did you last watch a child play and just enjoy it?',
  'What would you hear if you turned everything off?',
  'Find one thing today that you would have walked past.',
  'Be where your feet are.',
  'Listen for the furthest sound you can hear.',
  'When did you last give your full attention to a meal, a book or a person?',
  'What if this is the good part?',
  'Pay attention to the ordinary. It is what your life is made of.',
  'Stop reading for a moment and look up.',
  'What does silence feel like to you?',
  'What is happening outside right now, while you look at a screen?',
  'Are you here, or are you somewhere in your head?',
  'Notice the texture of whatever you’re holding.',
  'The moment you’re waiting for might be this one.',
  'When did you last watch the moon?',
  'What would it take to feel at home in this exact moment?',
  'Stop, just for a breath, before you rush into the next thing.',
  'Which of your daily moments would you miss most if they stopped?',
  'Your life is happening while you’re waiting for it to start.',
  'Let the next conversation be the only thing you’re doing.',
  'What would the child you once were notice about today?',
  'Can you find something new in a place you see every day?',
  'Presence is the gift you can give anyone, including yourself.',
  'What did the air smell like this morning?',
  'Look at your own hands. They have done so much.',
  'You don’t have to capture this. You can just live it.',
  'What part of today would you like to slow down?',
  'Take the long way home.',
  'Where was your attention when you woke up this morning?',
  'Who are you really listening to today?',
  'What if you didn’t need to be anywhere else?',
  'When did you last watch rain fall?',
  'Notice one kindness around you today.',
  'The next sunrise is not guaranteed. Notice the next one you see.',
  'What would change if you noticed more and hurried less?',
  'Sit somewhere new today, even if it’s just the other chair.',
  'How does this moment feel, without any judgement?',
  'Look at the stars the next clear night.',
  'Let the world be loud while you stay quiet for a moment.',
  'This breath. Then the next. That’s all there ever is.',
] as const
