/** How the hours and days are being spent. */
export const time = [
  'How would you spend today if it were one of your last?',
  'Where did yesterday go?',
  'What are you saving for “someday”?',
  'Someday is not a day of the week.',
  'What are you putting off that you actually want to do?',
  'You will never be this young again.',
  'Which hour of your day belongs only to you?',
  'What did you spend most of your time on this week? Was it worth it?',
  'If this year were your last, what would you stop doing?',
  'If this year were your last, what would you start?',
  'How much of today will you remember in a year?',
  'What are you waiting to be ready for?',
  'You don’t find time. You choose what gets it.',
  'What could you let go of to make room for what matters?',
  'Is your calendar a picture of your priorities?',
  'What would you do with a free afternoon, starting right now?',
  'The days are long, but the years are short.',
  'Which of today’s tasks will matter next month?',
  'What have you been “about to start” for years?',
  'Busy is not the same as full.',
  'When did you last lose track of time in a good way?',
  'What would you regret not having done if today were the end?',
  'How many more summers do you think you have?',
  'Most of your life is made of ordinary days. Make this one count.',
  'What part of your routine would you miss if it were gone?',
  'What will you do differently tomorrow?',
  'How much of your day is spent waiting for it to be over?',
  'A week from now, what will you wish you had done today?',
  'Which season of your life are you in?',
  'What is one thing you can do today that your future self will thank you for?',
  'Do you spend your mornings or does your phone?',
  'What have you been meaning to learn for years?',
  'Time spent well is never wasted, even if it produced nothing.',
  'How do you want to spend your evenings for the rest of your life?',
  'What would you do with an extra hour each day?',
  'Where does your time go when no one is watching?',
  'Is there something you do only because you always have?',
  'This moment will never happen again.',
  'Waiting for the right time is often a way of saying no.',
  'How many times have you said “next year”?',
  'What does a perfect ordinary day look like to you? How close was today?',
  'You have fewer weekends left than you think. What is this one for?',
  'Which minutes of today felt most alive?',
  'Are you rushing toward something, or away from something?',
  'Slow down long enough to notice what you are hurrying past.',
  'What will you make time for this week?',
  'What do you keep telling yourself you’ll do when things calm down?',
  'Things rarely calm down. Begin anyway.',
  'How long has it been since you did something for the first time?',
  'Which hours of your day do you give away without thinking?',
  'Today is the oldest you have ever been, and the youngest you will ever be.',
  'What would you do if you knew you had ten good years left?',
  'What would you do if you knew you had fifty good years left?',
  'A life is made of days like this one.',
  'What is your time worth to you? Do you charge enough for it?',
  'The time to plant a tree was years ago. The next best time is today.',
  'What did you do today that you’ll be glad you did?',
  'How much of your time goes to people who don’t matter to you?',
  'When was the last time you were bored? What did you notice?',
  'What would change if you treated this week as a gift?',
  'Is the pace of your life your choice?',
  'Would you want to live this week again?',
  'What are you doing now that you would never do if you had less time?',
  'What is the first thing you want to do tomorrow morning?',
  'Every “later” is borrowed from a future you can’t see.',
  'What are you counting down to? What are you missing on the way?',
  'Which activity always leaves you feeling your time was well spent?',
  'Which activity always leaves you feeling your time was wasted?',
  'How many hours today did you spend on something you love?',
  'When you are old, which days will you want back?',
  'The hours you spend scrolling are hours of your life.',
  'What if this weekend were the one you remember?',
  'What small thing could you do every day for the rest of your life?',
  'You are spending your life whether you mean to or not.',
  'What have you been postponing until you have more money, time or courage?',
  'Look at the clock. That minute is gone.',
  'Which year of your life would you most like to relive? Why?',
  'What does “enough time” mean to you?',
  'Are you living for the weekend? What would make the week worth it?',
  'What could you finish today, instead of starting something new?',
  'How would you spend a day with nothing planned?',
  'Plan less. Notice more.',
  'Which of your habits steals the most time from what you love?',
  'If today repeated forever, would you be content?',
  'What would you do today if you weren’t afraid of wasting it?',
  'The best moments rarely happen on schedule. Leave room for them.',
  'What have you already waited too long for?',
  'The days you are living now are the good old days of some future you.',
  'Do you give your best hours to your best things?',
  'How much of your life is spent preparing to live?',
  'What would your ideal Sunday look like? Could you have it this week?',
  'Take a walk with no destination and no time limit.',
  'Watch the sun go down tonight, if you can.',
  'Which moments of this week would you save, if you could keep only three?',
  'How old will you be when you finally do the thing?',
  'What is one thing you want to do every year until you die?',
  'Is there an hour of your week that you dread? Can you change it?',
  'Your time is the only thing you truly spend.',
  'What will you do with the rest of today?',
  'If you started now, where could you be in five years?',
] as const
