/** Work, ambition and what the effort is for. */
export const work = [
  'Will you wish you had worked more?',
  'What are you working toward, and will it be worth the cost?',
  'Who are you working for, really?',
  'What would you do for work if money didn’t matter?',
  'Is your job something you do, or something you are?',
  'What would you build if you knew no one would judge it?',
  'Which of your ambitions are yours, and which were handed to you?',
  'What does success look like when no one is watching?',
  'Have you confused being busy with being important?',
  'What part of your work would you do for free?',
  'What will your work leave behind?',
  'Is your career a ladder, or a path you chose?',
  'When did you last feel proud of your work?',
  'What would you stop doing if you weren’t afraid of what people would think?',
  'What would you like to be known for?',
  'Are you climbing toward something, or just climbing?',
  'Nobody’s last words were about the inbox.',
  'What skill would you love to master before you die?',
  'What would it take to love Mondays?',
  'Is there a project you care about that no one is paying you for?',
  'What are you trading your health for?',
  'What are you trading your evenings for?',
  'How much is enough?',
  'What would you do if you knew you couldn’t fail?',
  'What would you do if you knew you probably would fail, but it would be worth it?',
  'Which meeting this week could have been a walk?',
  'Are you proud of how you treat the people who work with you?',
  'Who helped your career without being asked? Have you thanked them?',
  'What would you tell your younger self about work?',
  'Your job title will not be on your tombstone.',
  'Is there a risk you keep talking yourself out of?',
  'What do you want to have made by the end of your life?',
  'Do you do your work, or does your work do you?',
  'When did you last do something just because it was interesting?',
  'What could you teach someone that took you years to learn?',
  'Who could you mentor?',
  'What does good work feel like, from the inside?',
  'Rest is part of the work.',
  'What would you do differently if you were starting your career today?',
  'Is your ambition making you better, or just more tired?',
  'What problem in the world do you wish you could help solve?',
  'Would you want your children to have your working life?',
  'Which part of your day do you look forward to most at work?',
  'What would you do with a year off?',
  'Is there a dream you’ve filed under “unrealistic”?',
  'How much of your worth do you measure in productivity?',
  'You are more than what you produce.',
  'What would you make if you had one more free hour a day?',
  'Are you building a life, or just a CV?',
  'What would you regret not trying?',
  'When did you last create something with your hands?',
  'Does your work give you energy, or take it?',
  'Who do you become when you work too much?',
  'What does “enough” look like for your career?',
  'Are you chasing a number that will never feel big enough?',
  'What would you still do after you retire?',
  'Would the person you were at twenty respect your working life?',
  'Is there something you’re good at that you’ve stopped doing?',
  'Craft is a way of paying attention. What do you pay attention to?',
  'Is your inbox deciding your priorities?',
  'Finish something small today, and let it be enough.',
  'What will you do when no one needs your work anymore?',
  'Whose approval are you still working for?',
  'The work you are proudest of: when did you do it, and why?',
  'What if you worked on one thing, fully, for an hour?',
  'Does your work make anyone’s life better? Whose?',
  'What would it mean to do your work with love?',
  'Where are you hiding behind “I’m too busy”?',
  'What would you attempt if you had nothing to prove?',
  'Is there a door you’ve been afraid to knock on?',
  'Which job would you take if you were brave?',
  'Your time at work is still your life.',
  'When did you last ask for what you are worth?',
  'What have you learned this year that you didn’t know last year?',
  'How would you work differently if you had one year left?',
  'Could you leave work on time today?',
  'What would it take to feel you had done enough today?',
  'Ambition is a good servant and a poor master.',
  'Would you swap your salary for more time? How much?',
  'What unfinished project still calls to you?',
  'Is the goal you’re chasing still the one you want?',
  'What would you do if you were twice as brave at work?',
  'Nobody remembers a deadline. People remember how you treated them.',
  'Who at work deserves more credit than they get?',
  'What do you want your working days to feel like?',
  'Your best work might still be ahead of you.',
  'What would you make if it only had to please you?',
  'Is there a way to do less and matter more?',
  'When you imagine retiring, what are you relieved to stop?',
  'What are you saving for retirement that you could start doing now?',
  'What are you secretly hoping someone will give you permission to do?',
  'You don’t need permission.',
  'What would you work on if your life depended on it being meaningful?',
  'What did you want to be when you were a child? What was that really about?',
  'How do you want to feel on the last day of your career?',
  'Is your work a way of avoiding something else in your life?',
  'Is there someone whose career you envy? What does that tell you?',
  'Do the thing you keep saying you’ll do when you have time.',
  'Measure your career in people you’ve helped, not titles you’ve held.',
  'What would be enough to call your working life a good one?',
] as const
